- hosts: all
  tasks:
    - name: Pull Docker Image
      command: docker pull tanvikulkarni33/scientific-calculator

    - name: Run Docker Container
      command: docker run -d --name calculator tanvikulkarni33/scientific-calculator
