- hosts: local
  become: yes
  tasks:
    - name: Ensure Docker SDK is installed
      pip:
        name: docker
        state: present

    - name: Remove old Docker image (if exists)
      community.docker.docker_image:
        name: tanvikulkarni33/scientific-calculator
        state: absent

    - name: Pull the latest Docker image (force pull)
      community.docker.docker_image:
        name: tanvikulkarni33/scientific-calculator:latest
        source: pull
        force_source: yes
        timeout: 300

    - name: Remove old container (if exists)
      community.docker.docker_container:
        name: scientific-calculator
        state: absent

    - name: Run the container
      community.docker.docker_container:
        name: scientific-calculator
        image: tanvikulkarni33/scientific-calculator:latest
        state: started
        restart_policy: always
        recreate: yes
        ports:
          - "8080:3000"  # Change this based on your application port
